//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazarTech.QueryableValues.EF6.SqlServer.Tests.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyEntity
    {
        public int MyEntityID { get; set; }
        public int PropA { get; set; }
        public long PropB { get; set; }
        public string PropC { get; set; }
        public System.DateTime PropD { get; set; }
        public Nullable<System.DateTime> PropE { get; set; }
    }
}
