//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazarTech.QueryableValues.EF6.SqlServer.Tests.DatabaseFirst
{
    using System;
    using System.Collections.Generic;

    public partial class TestDataEntity
    {
        public int Id { get; set; }
        public bool BoolValue { get; set; }
        public byte ByteValue { get; set; }
        public short Int16Value { get; set; }
        public int Int32Value { get; set; }
        public long Int64Value { get; set; }
        public decimal DecimalValue { get; set; }
        public float SingleValue { get; set; }
        public double DoubleValue { get; set; }
        public string StringValue { get; set; }
        public string StringUnicodeValue { get; set; }
        public System.DateTime DateTimeValue { get; set; }
        public System.DateTimeOffset DateTimeOffsetValue { get; set; }
        public System.Guid GuidValue { get; set; }
    }
}
